# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rich Notifications' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Pushbots', '~> 2.0.4'

  # Pods for Rich Notifications

  target 'Rich NotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rich NotificationsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
