# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RichNotificationExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Pushbots', '~> 2.0.4'


  # Pods for RichNotificationExample

  target 'RichNotificationExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RichNotificationExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
