# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeepLinkingObjc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Pushbots', '~> 2.0.4'

  # Pods for DeepLinkingObjc

end
